package zabeenia.prismaticcarpets;

public class PrismaticLoomSelections {

    public static final String[] PATTERNS = {
            "prismatic_ivy",
            "prismatic_autumn_leaves",
            "prismatic_pumpkins",
            "prismatic_jackolantern",
            "prismatic_ghost",
            "prismatic_skull",
            "prismatic_poison",
            "prismatic_barrel",
            "prismatic_cat",
            "prismatic_colibri",
            "prismatic_floral_navy",
            "prismatic_kevin",
            "prismatic_purple_kevin_mania",
            "prismatic_ocean",
            "prismatic_pig",
            "prismatic_sheep",
            "prismatic_swords",
            "prismatic_shamrock",
            "prismatic_ornament_black",
            "prismatic_ornament_gold",
            "prismatic_ornament_gray",
            "prismatic_ornament_navy",
            "prismatic_ornament_red",
            "prismatic_ornament_white"
    };

    public static final String[] BORDERS = {
            "prismatic_border_ivy",
            "prismatic_border_autumn",
            "prismatic_border_classic_black",
            "prismatic_border_classic_gray",
            "prismatic_border_classic_green",
            "prismatic_border_classic_navy",
            "prismatic_border_classic_orange",
            "prismatic_border_classic_pink",
            "prismatic_border_classic_purple",
            "prismatic_border_classic_red",
            "prismatic_border_classic_white",
            "prismatic_border_classic_yellow",
            "prismatic_border_corner_black",
            "prismatic_border_corner_gray",
            "prismatic_border_corner_green",
            "prismatic_border_corner_navy",
            "prismatic_border_corner_orange",
            "prismatic_border_corner_pink",
            "prismatic_border_corner_purple",
            "prismatic_border_corner_red",
            "prismatic_border_corner_white",
            "prismatic_border_corner_yellow",
            "prismatic_border_greek_black",
            "prismatic_border_greek_gray",
            "prismatic_border_greek_green",
            "prismatic_border_greek_navy",
            "prismatic_border_greek_orange",
            "prismatic_border_greek_pink",
            "prismatic_border_greek_purple",
            "prismatic_border_greek_red",
            "prismatic_border_greek_white",
            "prismatic_border_greek_yellow",
            "prismatic_border_zigzag_black",
            "prismatic_border_zigzag_gray",
            "prismatic_border_zigzag_green",
            "prismatic_border_zigzag_navy",
            "prismatic_border_zigzag_orange",
            "prismatic_border_zigzag_pink",
            "prismatic_border_zigzag_purple",
            "prismatic_border_zigzag_red",
            "prismatic_border_zigzag_white",
            "prismatic_border_zigzag_yellow"
    };
}
